#page title
page_title                                : BoxStream                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                         # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://tets                                        # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/AppLogo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Box Stream                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free & Enjoy                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Best Application for watching movies on Android

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ahmed Dikha                                
your_link                                 :https://github.com/bestwall2
your_city                                 : Beni Mellal                               
email_address                             : ahmed.dikha26@gmail.com
facebook_username                         : Ahmed26DIA                               
instagram_username                        : _a_h_m_e_d_d_i_e_
twitter_username                          : 
github_username                           : bestwall2
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Subtitles
    description                           : You may choose the default language of the subtitles to English or any other language. It supports over 25 Languages such as Spanish, Romanian, Portuguese, Polish, Latin, French, Thai, Turkish, Arabic and German, etc.
    fontawesome_icon_name                 : magic
    

  - title                                 : HD Content Options
    description                           : It has a big catalogue of HD Movies and TV Shows for all it's users.
    fontawesome_icon_name                 : play-circle

  - title                                 : Regular Updates
    description                           : BOX STREAM is very keen to provide regular updates to the app to keep it bug free. So, users will get timely updates to the content and to the app's version as well.
    fontawesome_icon_name                 : sync

  - title                                 : Wacth List
    description                           : Now you can save your favorite movies to watch it later, If You Sign in, Your Watch list will be Saved 4ever.
    fontawesome_icon_name                 : star

  - title                                 : Support And FeedBack 
    description                           : We will work on all the problems that the user faces and we will work hard to fix them.
    fontawesome_icon_name                 : info-circle




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/Bg.png                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
